### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by DTXGAMERYT** [BolisettySujith/J.A.R.V.I.S#18] opened 2023-01-01 09:47 UTC
if i run the code python opens a new tab named main and i get half of screen i cannot see full screen so i cant run jarvis
![image](https://user-images.githubusercontent.com/76437596/210166719-1cd90048-32f6-4328-ab99-100049af1e93.png)

**Comment by BolisettySujith** [comment] 2023-01-01 10:46
Hello @DTXGAMERYT 

Actually, it's not a bug, the application is not responsive, and the resolution of the screen is made according to my screen, for the small screen it may enlarge, So if you are interested you can make it responsive and I'm happy to accept the PR.


Thank you.

**Comment by DTXGAMERYT** [comment] 2023-01-01 12:50
can u help me where can i change resolution?

**Comment by BolisettySujith** [comment] 2023-01-01 16:27
You can change that from JarvisUI.py [Lines:17](https://github.com/BolisettySujith/J.A.R.V.I.S/blob/main/JarvisUi.py#L17).

**Comment by BolisettySujith** [comment] 2023-01-16 18:50
@DTXGAMERYT  Closing this issue, if you still have any other issue, please feel free to open a new issue.

**Closed by BolisettySujith** 2023-01-16 18:50 UTC
Labels: bug
