### ISSUE TITLE
Bug: Not Replying Back and UI Bug

### ISSUE THREAD

**Issue by anny414** [BolisettySujith/J.A.R.V.I.S#19] opened 2023-01-12 02:32 UTC
When I run the cmd `python JARVIS.py` It Keeps says Listening reputedly even after I press q As said in [ERROR.md](https://github.com/BolisettySujith/J.A.R.V.I.S/blob/main/ERRORS/ERRORS.md)  
hear a screenshot 
![Screenshot_20230112_075702](https://user-images.githubusercontent.com/72495984/211961804-6fb93674-1fc9-4f48-89e3-ab64917f905d.png)

![Screenshot_20230112_075651](https://user-images.githubusercontent.com/72495984/211961846-e0402899-3e46-434e-b5ca-57a995f79468.png)

Also When I press Run All gif files disappear
screenshots 
before Run 
![Screenshot_20230112_075619](https://user-images.githubusercontent.com/72495984/211961983-3e6e0ff9-6dcd-4485-8b41-1d93bbe0447e.png)
After Run 
![Screenshot_20230112_075638](https://user-images.githubusercontent.com/72495984/211962026-b2b3baa7-6ab3-47d9-badd-d469b2b1695f.png)

Please Help me if you can

**Comment by BolisettySujith** [comment] 2023-01-12 09:04
@anny414 is there any error displaying in the console after you Run it?

Keyword **q** is used to stop the screen recording, so listening won't be stopped.

**Comment by anny414** [comment] 2023-01-14 06:13
it keep repting listening None listening No error in console

**Comment by anny414** [comment] 2023-01-16 17:03
@BolisettySujith Can you tell anything please

**Comment by BolisettySujith** [comment] 2023-01-16 17:10
Actually, it will listen for a certain amount of time every time and checks listens to nothing it will return None, otherwise, it will return what you have talked.

![image](https://user-images.githubusercontent.com/73323807/212732691-0f4aab8b-c8b7-4c70-a23b-26481f726fcb.png)
In the screenshot that you have provided, it returns **hello**, that means at the time it is listening you talked *hello*, and at the time it is not listening you didn't talk anything.

**Comment by BolisettySujith** [comment] 2023-01-16 18:18
@anny414 As you raised the issue, I just cross check it

It's working completely fine for me.
Screenshot:
![image](https://user-images.githubusercontent.com/73323807/212743823-75eb0def-d1c3-4ecc-a399-1168fd428559.png)

When I talk `wake up` it responds with the suitable msg.

**Comment by BolisettySujith** [comment] 2023-01-16 18:20
About the elements Invisible issue it's due to the path is hard coded in the project, if update it according to your path it will work fine.

Anyways many ppl many faced this issue, I will update the code.

**Comment by BolisettySujith** [comment] 2023-01-30 09:50
I assume the issue is fixed so I'm closing the issues.

**Closed by BolisettySujith** 2023-01-30 09:50 UTC
Labels: bug
